name: RTSMP
version: 1.0
author: Mistri
main: com.jmistri.rtsmp.Main
api-version: 1.14
commands:
   ping:
      description: Get the ping of a player
      usage: /ping
   day:
      description: Start a countdown to set the game to daytime
      usage: /day
   night:
      description: Cancel the daytime command countdown
      usage: /night